import type { Metadata } from "next";
import { Figtree, Oswald } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Newsletter from "@/components/layout/newslatter";
import { CartProvider } from "@/contexts/cart-context";
import { ReactQueryProvider } from "@/contexts/react-query-provider";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/next";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree-sans",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${oswald.variable} antialiased`}>
        <ReactQueryProvider>
          <CartProvider>
            {/* Top Banner */}
            <div className="bg-[#1A1A1C] text-center py-2.5 px-7.5 border-b-gray-700 border-b-[1px]">
              <p className="font-heading text-base md:text-xl text-[#E8E8E8] font-medium tracking-widest">
                LIVRAISON GRATUITE POUR LES COMMANDES DE PLUS DE 50 $
              </p>
            </div>
            <Header />
            {children}
            <Analytics />
            <Toaster />

            <Newsletter />
          </CartProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
